language: swift
os: osx
osx_image: xcode10.1

branches:
  only:
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

xcode_project: DemoTest/DemoTest.xcodeproj
xcode_scheme: 
  - TVNExtensions
  - DemoTest
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X
podfile: DemoTest/PodFile