language: swift
xcode_project: DemoTest/DemoTest.xcodeproj
xcode_scheme: DemoTest, DemoTestTests, DemoTestUITests
xcode_destination: platform=iOS Simulator,OS=12,name=iPhone X
podfile: DemoTest/PodFile
os: osx
osx_image: xcode10.1
before_install:
  - pod instal --repo-update