language: swift
xcode_project: DemoTest/DemoTest.xcodeproj
xcode_scheme: DemoTestTests, DemoTestUITests
xcode_destination: platform=iOS Simulator,OS=12,name=iPhoneX
podfile: DemoTest/PodFile
os: osx
osx_image: xcode10.1