language: swift
os: osx
osx_image: xcode11.2

branches:
  only:
    - master
    - RX

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

xcode_workspace: DemoTest/DemoTest.xcworkspace
xcode_scheme: 
  - DemoTest

xcode_destination: platform=iOS Simulator,OS=13.2,name=iPhone 11
podfile: DemoTest/PodFile

before_install:
  - brew install swiftlint
  - gem install cocoapods -v 1.7.3
  - npm install
  - pod repo update

notifications:
  email:
    recipients:
      - tienvn3845@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
