disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace

identifier_name:
  min_length: 2

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - DemoTestUITests
  - DemoTestTests