# Uncomment the next line to define a global platform for your project
#platform :ios, '8.4'

target 'DemoTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoTest
  pod 'TVNExtensions', :path => '../.'
  pod 'ParticleIOS', :path => '../.'
  pod 'TlvParser', :path => '../.'
  pod 'TVNExtensions/Kingfisher', :path => '../.'
  pod 'TVNExtensions/Rx', :path => '../.'

  target 'DemoTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
