# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_14.1.app
    - name: Install Dependencies
      run: |
        cd DemoTest
        pod install --repo-update
      shell: bash
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
